name: balena

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        fleet:
          [
            gh_klutchell/tailscale-aarch64,
            gh_klutchell/tailscale-amd64,
            gh_klutchell/tailscale-armv7hf,
          ]

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false
          fetch-depth: 1
      # https://github.com/balena-io/deploy-to-balena-action
      - uses: balena-io/deploy-to-balena-action@63a685c4b9c898c38e66776284a78c4e50ec8c97 # v2.0.136
        with:
          balena_token: ${{ secrets.BALENA_API_KEY }}
          fleet: ${{ matrix.fleet }}
